---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role luigid
# 

#
# vars are namespaced with the module name.
#

LUIGID_GIT_IDENTITY: !!null
LUIGID_VERSION: "edx/release"
LUIGID_SERVICE_CONFIG: {}

LUIGID_REPOS:
  - PROTOCOL: "{{ COMMON_GIT_PROTOCOL }}"
    DOMAIN: "{{ COMMON_GIT_MIRROR }}"
    PATH: "{{ COMMON_GIT_PATH }}"
    REPO: luigi.git
    VERSION: "{{ LUIGID_VERSION }}"
    DESTINATION: "{{ luigid_code_dir }}"
    SSH_KEY: "{{ LUIGID_GIT_IDENTITY }}"

#
# vars are namespace with the module name.
#

luigid_service_name: "luigid"
luigid_user: "{{ luigid_service_name }}"
luigid_home: "{{ COMMON_APP_DIR }}/{{ luigid_service_name }}"
luigid_code_dir: "{{ luigid_home }}/{{ luigid_service_name }}"
luigid_log_dir: "{{ COMMON_LOG_DIR }}/{{ luigid_service_name }}"

luigid_venv_dir: "{{ luigid_home }}/venvs/{{ luigid_service_name }}"

luigid_conf_dir: "/etc/luigi"
luigid_pidfile_path: "/var/run/luigid.pid"
luigid_bind_address: "0.0.0.0"
luigid_port: 9100

luigid_config:
  record_task_history: "True"

luigid_task_history_connection: "sqlite:////var/tmp/luigi-task-hist.db"

luigid_python_requirements:
  - "SQLAlchemy==1.1.4"
  - "tornado==4.4.2"

#
# OS packages
#

luigid_debian_pkgs: []

luigid_redhat_pkgs: []
