---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role hive
# 
# Overview:
# 
# Install and configure Hive.
#
# Dependencies:
#
# hadoop_common: Hive requires Hadoop to be installed to function properly.


- name: check if downloaded and extracted
  stat:
    path: "{{ HIVE_HOME }}"
  register: extracted_dir
  tags:
    - install
    - install:system-requirements

- name: distribution downloaded
  get_url:
    url: "{{ hive_dist.url }}"
    sha256sum: "{{ hive_dist.sha256sum }}"
    dest: "{{ hive_temporary_dir }}"
  when: not extracted_dir.stat.exists
  tags:
    - install
    - install:system-requirements

- name: distribution extracted
  shell: "tar -xzf {{ hive_temporary_dir }}/{{ hive_dist.filename }} && chown -R {{ hadoop_common_user }}:{{ hadoop_common_group }} hive-{{ HIVE_VERSION }}-bin"
  args:
    chdir: "{{ HADOOP_COMMON_USER_HOME }}"
  when: not extracted_dir.stat.exists
  tags:
    - install
    - install:system-requirements

- name: versioned directory symlink created
  file:
    src: "{{ HADOOP_COMMON_USER_HOME }}/hive-{{ HIVE_VERSION }}-bin"
    dest: "{{ HIVE_HOME }}"
    owner: "{{ hadoop_common_user }}"
    group: "{{ hadoop_common_group }}"
    state: link
  tags:
    - install
    - install:system-requirements

- name: environment configuration installed
  template:
    src: "hive-env.sh.j2"
    dest: "{{ HIVE_CONF }}/hive-env.sh"
    mode: 0640
    owner: "{{ hadoop_common_user }}"
    group: "{{ hadoop_common_group }}"
  tags:
    - install
    - install:system-requirements

- name: hive configured
  hadoop_configuration:
    property: "{{ item.key }}"
    value: "{{ item.value }}"
    path: "{{ HIVE_CONF }}/hive-site.xml"
  become_user: "{{ hadoop_common_user }}"
  with_dict: hive_site_config
  tags:
    - install
    - install:system-requirements

- name: env vars sourced in hadoop env
  lineinfile:
    dest: "{{ hadoop_common_env }}"
    state: present
    regexp: "^. {{ HIVE_CONF }}/hive-env.sh"
    line: ". {{ HIVE_CONF }}/hive-env.sh"
  tags:
    - install
    - install:system-requirements
