---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role hive
# 

HIVE_VERSION: 0.11.0
HIVE_HOME: "{{ HADOOP_COMMON_USER_HOME }}/hive"
HIVE_CONF: "{{ HIVE_HOME }}/conf"
HIVE_LIB: "{{ HIVE_HOME }}/lib"

#
# vars are namespace with the module name.
#
hive_role_name: hive
hive_temporary_dir: /var/tmp
hive_dist:
  filename: "hive-{{ HIVE_VERSION }}-bin.tar.gz"
  url: "https://archive.apache.org/dist/hive/hive-{{ HIVE_VERSION }}/hive-{{ HIVE_VERSION }}-bin.tar.gz"
  sha256sum: c22ee328438e80a8ee4b66979dba69650511a73f8b6edf2d87d93c74283578e5

hive_site_config:
  javax.jdo.option.ConnectionURL: jdbc:derby:;databaseName=/var/tmp/metastore_db;create=true

#
# OS packages
#

hive_debian_pkgs: []

hive_redhat_pkgs: []
