---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Role includes for role luigid
# 
# Example:
#
# dependencies:
#   - {
#   role: my_role 
#   my_role_var0: "foo"
#   my_role_var1: "bar"
# }

dependencies:
  - common
  - role: edx_service
    edx_service_name: "{{ luigid_service_name }}"
    edx_service_config: "{{ LUIGID_SERVICE_CONFIG }}"
    edx_service_repos: "{{ LUIGID_REPOS }}"
    edx_service_user: "{{ luigid_user }}"
    edx_service_home: "{{ luigid_home }}"
    edx_service_packages:
      debian: "{{ luigid_debian_pkgs }}"
      redhat: "{{ luigid_redhat_pkgs }}"