---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role analytics_pipeline
#
ANALYTICS_PIPELINE_GIT_IDENTITY: !!null
ANALYTICS_PIPELINE_VERSION: master

ANALYTICS_PIPELINE_WHEEL_URL: http://edx-wheelhouse.s3-website-us-east-1.amazonaws.com/Ubuntu/precise
ANALYTICS_PIPELINE_PYTHON_VERSION: 2.7
ANALYTICS_PIPELINE_PYTHON: "/usr/bin/python{{ ANALYTICS_PIPELINE_PYTHON_VERSION }}"

ANALYTICS_PIPELINE_REPOS:
  - PROTOCOL: "{{ COMMON_GIT_PROTOCOL }}"
    DOMAIN: "{{ COMMON_GIT_MIRROR }}"
    PATH: "{{ COMMON_GIT_PATH }}"
    REPO: edx-analytics-pipeline.git
    VERSION: "{{ ANALYTICS_PIPELINE_VERSION }}"
    DESTINATION: "{{ analytics_pipeline_code_dir }}"
    SSH_KEY: "{{ ANALYTICS_PIPELINE_GIT_IDENTITY }}"

ANALYTICS_PIPELINE_SERVICE_CONFIG: {}
ANALYTICS_PIPELINE_DATABASES: {}
HADOOP_COMMON_RESOURCE_MANAGER_HOST: resourcemanager
HADOOP_DEFAULT_FS: hdfs://namenode:8020

ANALYTICS_PIPELINE_LUIGI_HADOOP_VERSION: cdh4
ANALYTICS_PIPELINE_LUIGI_HADOOP_COMMAND: "{{ HADOOP_COMMON_HOME }}/bin/hadoop"
ANALYTICS_PIPELINE_LUIGI_HADOOP_STREAMING_JAR: "{{ HADOOP_COMMON_HOME }}/share/hadoop/tools/lib/hadoop-streaming-{{ HADOOP_COMMON_VERSION }}.jar"

#
# vars are namespaced with the module name.
#
analytics_pipeline_role_name: analytics_pipeline

analytics_pipeline_util_library:
  path: /var/tmp/edx-analytics-hadoop-util
  repo: https://github.com/edx/edx-analytics-hadoop-util
  version: master

analytics_pipeline_service_name: analytics_pipeline

analytics_pipeline_venv_dir: "{{ analytics_pipeline_home }}/venvs/{{ analytics_pipeline_service_name }}"
analytics_pipeline_user: "{{ analytics_pipeline_service_name }}"
analytics_pipeline_home: "{{ COMMON_APP_DIR }}/{{ analytics_pipeline_service_name }}"
analytics_pipeline_code_dir: "{{ analytics_pipeline_home }}/{{ analytics_pipeline_service_name }}"
analytics_pipeline_log_dir: "{{ COMMON_LOG_DIR }}/{{ analytics_pipeline_service_name }}"
analytics_pipeline_config_dir: "{{ COMMON_CFG_DIR }}/{{ analytics_pipeline_service_name }}"

analytics_pipeline_install_env:
    WHEEL_URL: "{{ ANALYTICS_PIPELINE_WHEEL_URL }}"
    WHEEL_PYVER: "{{ ANALYTICS_PIPELINE_PYTHON_VERSION }}"

#
# OS packages
#

analytics_pipeline_debian_pkgs: []

analytics_pipeline_redhat_pkgs: []
